export const ingAllData = [
  {
    id: 1,
    name: "올리브 오일 엑스트라 버진",
    weight: 85.0,
    incRate: 67.3,
    etcEffect: "산도 0.8% 이하 최고급 올리브유",
    store: "네이버 쇼핑 스토어",
    buyUnit: "5 리터(캔/플라그틱 용기)",
    price: "3 만원 내외(3 천원)",
    desc: "올리브 오일은 산도가 낮을 수록 고품질로 여겨지는데, "
    + "산도 0.8% 이하이면, 최고 등급인 엑스트라 버진으로 분류된다. "
    + "올리브 오일은 영상 8℃ 이하에서 하얗게 굳는 성질이 있고, " 
    + "용기 하부에 올리브 열매 침전물이 생길 수 있다.",
    image: "olive-oil.jpg"
  },
  {
    id: 2,
    name: "정제수",
    weight: 25.5,
    incRate: 20.2,
    etcEffect: "",
    store: "",
    buyUnit: "",
    price: "",
    desc: "",
  },
  {
    id: 3,
    name: "가성소다(소듐하이드록사이드)",
    weight: 11.3,
    incRate: 8.9,
    etcEffect: "",
    store: "",
    buyUnit: "",
    price: "",
    desc: "",
  },
  {
    id: 4,
    name: "제주 비자나무 향오일",
    weight: 3.4,
    incRate: 2.7,
    etcEffect: "(레몬, 감귤 등에 있는)시트랄, 리모넨 함유",
    store: "",
    buyUnit: "",
    price: "",
    desc: "",
  },
  {
    id: 5,
    name: "어성초 분말(약모밀 가루)",
    weight: 0.55,
    incRate: 0.45,
    etcEffect: "피부 개선 - 동의보감 참조",
    store: "",
    buyUnit: "",
    price: "",
    desc: "",
  },
  {
    id: 6,
    name: "율무 분말",
    weight: 0.55,
    incRate: 0.45,
    etcEffect: "피부 대사 증진 - 동의보감 참조",
    store: "",
    buyUnit: "",
    price: "",
    desc: "",
  },
  {
    id: "",
    name: "합",
    weight: 126.3,
    incRate: 100,
    etcEffect: "",
  },
];
